server:
  port: 8080

spring:
  profiles:
    active: qa
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Jaidhev_2003@sql
    url: jdbc:mysql://localhost:3306/springdatabase-qa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
welcome:
  message: Welcome to Daily Code Buffer!!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
